"""init_migration

Revision ID: 5fa1ffbb60a1
Revises: 
Create Date: 2022-10-12 23:28:06.055408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fa1ffbb60a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('channel_id', sa.String(length=20), nullable=False),
    sa.Column('team_id', sa.String(length=20), nullable=False),
    sa.Column('channel_name', sa.String(), nullable=False),
    sa.Column('cron', sa.String(), nullable=True),
    sa.Column('cron_tz', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(length=20), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.channel_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('daily_status', sa.Boolean(), nullable=False),
    sa.Column('q_idx', sa.Integer(), nullable=True),
    sa.Column('main_channel_id', sa.String(length=20), nullable=False),
    sa.Column('real_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['main_channel_id'], ['channels.channel_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily',
    sa.Column('thread_ts', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('thread_ts')
    )
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('attachment', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachments')
    op.drop_table('daily')
    op.drop_table('answers')
    op.drop_table('users')
    op.drop_table('questions')
    op.drop_table('channels')
    # ### end Alembic commands ###
